version: "3.8"
services: 
  app:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - .:/app
    ports: 
      - 3000:3000
    image: app:tictoetacimage
    container_name: tictoetac_container
    command: npm start